# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x07\x65xample\"\x1b\n\x0bUnitRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tUnitReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x08UnitText\x12\x0c\n\x04text\x18\x01 \x01(\t2p\n\x07Greeter\x12\x33\n\x05Units\x12\x14.example.UnitRequest\x1a\x12.example.UnitReply\"\x00\x12\x30\n\x06Units2\x12\x11.example.UnitText\x1a\x11.example.UnitText\"\x00\x62\x06proto3')
)




_UNITREQUEST = _descriptor.Descriptor(
  name='UnitRequest',
  full_name='example.UnitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.UnitRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)


_UNITREPLY = _descriptor.Descriptor(
  name='UnitReply',
  full_name='example.UnitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='example.UnitReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=80,
)


_UNITTEXT = _descriptor.Descriptor(
  name='UnitText',
  full_name='example.UnitText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='example.UnitText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['UnitRequest'] = _UNITREQUEST
DESCRIPTOR.message_types_by_name['UnitReply'] = _UNITREPLY
DESCRIPTOR.message_types_by_name['UnitText'] = _UNITTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnitRequest = _reflection.GeneratedProtocolMessageType('UnitRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNITREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.UnitRequest)
  ))
_sym_db.RegisterMessage(UnitRequest)

UnitReply = _reflection.GeneratedProtocolMessageType('UnitReply', (_message.Message,), dict(
  DESCRIPTOR = _UNITREPLY,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.UnitReply)
  ))
_sym_db.RegisterMessage(UnitReply)

UnitText = _reflection.GeneratedProtocolMessageType('UnitText', (_message.Message,), dict(
  DESCRIPTOR = _UNITTEXT,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:example.UnitText)
  ))
_sym_db.RegisterMessage(UnitText)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='example.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=108,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='Units',
    full_name='example.Greeter.Units',
    index=0,
    containing_service=None,
    input_type=_UNITREQUEST,
    output_type=_UNITREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Units2',
    full_name='example.Greeter.Units2',
    index=1,
    containing_service=None,
    input_type=_UNITTEXT,
    output_type=_UNITTEXT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
